import { Metadata } from "next";
import ThemeWrapper from "./ThemeWrapper";
import "./globals.css";
import Navbar from "@/components/NavigationComponents/Navbar";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Eksab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className="antialiased">
        <ThemeWrapper>
          <Navbar />
          <div className="mt-20">{children}</div>
          <Footer />
        </ThemeWrapper>
      </body>
    </html>
  );
}
