import { Metadata } from "next";
import ThemeWrapper from "./ThemeWrapper";
import "./globals.css";

export const metadata: Metadata = {
  title: "Eksab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className="antialiased">
        <ThemeWrapper>{children}</ThemeWrapper>
      </body>
    </html>
  );
}
